title: 가루 # your site title
author: 가루아빠
email: djsdj2@naver.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  안녕하세요 일본에서 가루랑 같이 살고 있는 개발자 입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://Kimgaru.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 가루아빠 # replace with your_twitter_username or comment to remove link from footer
github_username:  Kimgaru # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer
social:
  name: 가루아빠
  links:

disqus:
  shortname: 가루 # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
